# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
# Reflected Code: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py
# Config Docs: https://docs.deepwisdom.ai/main/en/guide/get_started/configuration.html
# llm:
#   api_type: "openai"  # or azure / ollama / groq etc.
#   model: "gpt-4-turbo"  # or gpt-3.5-turbo
#   base_url: "https://api.openai.com/v1"  # or forward url / other llm url
#   api_key: "YOUR_API_KEY"

llm:
  api_type: "openai"
  model: "Qwen/Qwen3-4B"  # IMPORTANT: Change this to the model you are serving with vLLM
  base_url: "http://127.0.0.1:8000/v1" 
  api_key: "token-abc123"

models:
 "Qwen/Qwen3-4B": # IMPORTANT: Change this to the model you are serving with vLLM
   api_type: "openai"
   base_url: "http://127.0.0.1:8000/v1"
   api_key: "token-abc123"
   temperature: 0
# "zai-org/GLM-4-9B-0414": # IMPORTANT: Change this to the model you are serving with vLLM
#    api_type: "openai"
#    base_url: "http://127.0.0.1:8000/v1"
#    api_key: "token-abc123"
#    temperature: 0
CALC_USAGE: True 